### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jpliew** [Simpleyyt/jekyll-simpleyyt#1]
Hi,
May I know which search plugin were you intend to use please? There was a search box but not related to and search plugin.

Cheers
JP

**Comment by Simpleyyt** [comment]
Hi Cheers, I added the google custom search to the blog just now.

**Comment by jpliew** [comment]
Thanks. Very clean and nice work.

I have also added https://github.com/slashdotdash/jekyll-lunr-js-search

**Comment by Simpleyyt** [comment]
good job!
