### ISSUE TITLE
你好，关于这个博客模版一些问题

### ISSUE THREAD

**Issue by flight2006** [Simpleyyt/jekyll-simpleyyt#4]
使用了你这个简洁的模版，感觉不错，有点疑问：
1.博客正文怎么贴图？看了你的一些博客好像都没有贴图的，是不是不支持？
2.用一个tab显示代码高亮，但是段头空格好像冲突了

**Comment by Simpleyyt** [comment]
博客都是用markdown语言写的，具体可以参考：http://wowubuntu.com/markdown/
贴图博客：http://simpleyyt.github.io/linux/2014/04/16/sk_buff_analysis/

在 2015年4月18日 下午3:04，flight2006 notifications@github.com写道：

> 使用了你这个简洁的模版，感觉不错，有点疑问：
> 1.博客正文怎么贴图？看了你的一些博客好像都没有贴图的，是不是不支持？
> 2.用一个tab显示代码高亮，但是段头空格好像冲突了
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Simpleyyt/simpleyyt.github.io/issues/4.

## 

---

Best,

Yao Yitao

Sun Yat-Sen University

Email : simpleyyt@gmail.com
