### ISSUE TITLE
Markdown解析失败

### ISSUE THREAD

**Issue by Turbo-Snail** [Simpleyyt/jekyll-simpleyyt#7]
背景描述：我使用您的模板，在Github上能显示出Markdown编辑的效果，但是在博客上面Markdown语法的效果就失效了。具体可参考如下截图：

GitHub 截图
![Github截屏](https://user-images.githubusercontent.com/17407236/31305794-52d784e8-ab74-11e7-8aa1-ea4c196e31ef.jpg)

博客截图
![博客截屏](https://user-images.githubusercontent.com/17407236/31305812-d9eeeaf2-ab74-11e7-8dd1-ac7483875dd9.jpg)

我看您这一篇刚好是测试用的文件，是不是您当时也是遇到同样的问题？不知道后来怎么解决的。

我的尝试：

- 上 Jekyll 官方网站，查关于Markdown的配置问题。其中提到Markdown有三种配置方式，由于才接触 Github 和 Jekyll 不久，我能够理解的只有默认形式的Kramdown，我尝试在Github中做修正，结果无效。Kramdown 语法修正如下：

![Kramdown](https://user-images.githubusercontent.com/17407236/31306168-d689a14c-ab7c-11e7-87c2-87c341e41134.jpg)

剩下的关于 Redcarpet 和 自定义处理器，以我目前的水平，还理解不了具体应该怎么操作。

问题：

1. 您是怎么解决的？是否Kramdown的设置只要微调就可以，还是只能通过另外两个途径解决？
2. 如果需要通过 Redcarpet 来解决，有没有更详细的教程？

期待尽快得到回复。谢谢！

**Comment by Simpleyyt** [comment]
可以试试：
```
markdown: kramdown
kramdown:
    input: GFM
```

**Comment by Turbo-Snail** [comment]
非常感谢这么快回复。这个命令我也试过的，不管用。我再想想其他办法。谢谢啦！:)

**Comment by Turbo-Snail** [comment]
问题暂时无解，先关闭Issue。谢谢！
